apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.allow-http: "false"
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.subdomain }}.{{ .Values.hostname }}"
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  tls:
  - hosts:
    - "{{ .Values.subdomain }}.{{ .Values.hostname }}"
    secretName: hello-kubernetes-tls
  rules:
  - host: "{{ .Values.subdomain }}.{{ .Values.hostname }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hello-kubernetes
            port:
              number: 80
