# See https://github.com/bitnami/charts/tree/master/bitnami/external-dns
digitalocean:
  secretName: "digital-ocean-token"
interval: "15s"
provider: "digitalocean"
policy: "sync"
txtPrefix: "xdns-"
resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
